"""init

Revision ID: 93f5a2453130
Revises: 
Create Date: 2022-07-25 13:49:11.994234

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "93f5a2453130"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hero",
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "employment_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("salary", sa.Integer(), nullable=False),
        sa.Column("id_chief", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hero_employment_date"), "hero", ["employment_date"], unique=False
    )
    op.create_index(op.f("ix_hero_full_name"), "hero", ["full_name"], unique=False)
    op.create_index(op.f("ix_hero_id"), "hero", ["id"], unique=False)
    op.create_index(op.f("ix_hero_id_chief"), "hero", ["id_chief"], unique=False)
    op.create_index(op.f("ix_hero_job_title"), "hero", ["job_title"], unique=False)
    op.create_index(op.f("ix_hero_salary"), "hero", ["salary"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hero_salary"), table_name="hero")
    op.drop_index(op.f("ix_hero_job_title"), table_name="hero")
    op.drop_index(op.f("ix_hero_id_chief"), table_name="hero")
    op.drop_index(op.f("ix_hero_id"), table_name="hero")
    op.drop_index(op.f("ix_hero_full_name"), table_name="hero")
    op.drop_index(op.f("ix_hero_employment_date"), table_name="hero")
    op.drop_table("hero")
    # ### end Alembic commands ###
